#!/bin/bash
sh -c 'xsetwacom --set 14 Rotate half'
sh -c 'xsetwacom --set 15 Rotate half'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 1 "key ctrl"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 2 "key shift"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 3 "key alt"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 8 "key ctrl z"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 9 "key ctrl shift z"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 10 "key ctrl a"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 11 "key ctrl shift a"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 12 "key q"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 13 "key backspace"'
sh -c 'xsetwacom --set "HUION Huion Tablet_HS611 Pad pad" Button 14 "key esc"'
